:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= autozip(1)

== NAME

autozip - An automatic file compression tool.

== SYNOPSIS

autozip [source] [ext] [level] [options]

== DESCRIPTION

This will compress files and folders with extension [ext] to [level]. You can make [level] 1 (fastest) to 9 (best). Some algorithms (e.g. xzip, zip) may support 0 (store only; no compression). If [level] is omitted, will use default value provided by algorithm. If [ext] is also omitted, will use gz & tar.gz. If [source] is omitted, will check the algorithms installed on your computer and give back a list of available extension name.

== OPTIONS

include::include/cmnopt.adoc[]

`--force-parallel:[location]` Force to use GUN parallel at [location]. This will not affect pgzip, XZ Utils or other algorithms which do not require GNU Parallel.

`--force` Remove the target if exists.
`--remove` Remove [sorce] if success.

`-s[:[split]]|-split[:[split]]` Split the archive by [split]. This is realized by using GNU coreunits "split" or those provided in corresponding algorithms like 7zip, zip or rar. If [split] is omitted, it will be treated as 1G. legal [split] are those which can be recognized by GNU coreunits "split" or corresponding algorithms.

When making a tar.?z archive, this will split the tar file and compress them orderly.

When using zip format, we'll use `zip -FF` to merge the zips.

include::include/autozipcmn.adoc[]

== SEE ALSO

autounzip, azman

== INFORMATION ABOUT ALGORITHMS
	1.9G TDSGitServer
	478M TDSGitServer.txz
	479M TDSGitServer.7z
	540M TDSGitServer.rar
	580M TDSGitServer.tlz
	673M TDSGitServer.tbz
	718M TDSGitServer.zip
	719M TDSGitServer.tgz
	1.9G TDSGitServer.tar

include::include/copy.adoc[]
