:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= azman(1)

== NAME

azman - AutoZip file Manager.

== SYNOPSIS

`azman [subcommand]`

== DESCRIPTION

Execute `[subcommand]` which will be introduced bellow.
If there's no `[subcommand]` presented, the program will check the algorithms installed on your computer and return a list of available extension name.

WARNING: This program do not support archives with extension `.lzma`, `.lz` and `bzip2`.

== OPTIONS

* `-p[:[thread]]|--parallel[:[thread]]` Use `[thread]` threads when extracting the archive. `[thread]` should not be higher than the number of cores installed.
If `[thread]` is omitted, will use the number of cores installed.

include::include/cmnopt.adoc[]

== SUBCOMMANDS

`list [SOURCE1] [[SOURCE2]...]` List all files and folders inside `[SOURCE]` in a verbose format.

include::include/autozipcmn.adoc[]

== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== CYGWin

Tested with all functions supported.

== KNOWN BUGS

Cannot list splitted zip files which contains only 1 file.

== SEE ALSO

autozip, azman

include::include/copy.adoc[]
