:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= libisopt(1)

== NAME

libisopt - A library to check whether a parameter is a legal YuZJLab option.

== SYNOPSIS

`. /PATH/TO/LIBISOPT`

`isopt ${OPT}`

== DESCRIPTION

Firstly, use `. /PATH/TO/LIBISOPT` to import libisopt. (Command `source` is equal to command `.`)

Then, use loop to check if a parameter is an option.

Legal option can be classified into following classes:

* Option without addition parameter:

** A dash with a alphanum. e.g. `-h`

** Two dashes with multiple alphanum. e.g. `--help`

* For those options with addition parameter, those parameter are attached after `:`. e.g. `-s:10M` or `--split:10M`

That is, those parameter which matches the regular expression `-[^-\s]|--\S+|-[^-\s]\:\S+|--\S+:\S+`:

== EXAMPLE

```
OPT=()
STDS=()
for opt in "${@}"; do
    if isopt ${opt}; then
        case ${opt} in
        "-h" | "--help")
            # DOC command
            exit 0
            ;;
        "-v" | "--version")
            # VERSION command
            exit 0
            ;;
        *)
            echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
            exit 1
            ;;
        esac
        OPT=(${OPT[@]} "${opt}")
    else
        STDS=(${STDS[@]} "${opt}")
    fi
done
```

After this loop, options and other parameters are separated into string `${OPT}` and `${STDS}`. If there're unrecognized option, the program will exit with exit code 1.

include::include/copy.adoc[]
