:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= LMP_basis(1)

== NAME

LMP_Basis - The basic configuration of LinuxMiniPrograms.

== SYNOPSIS

yldoc LMP_basis

== DESCRIPTION

This is a descriptional manual; it shows you the basic configuration in LinuxMiniPrograms.

== PYTHON IN LMP

Although the frmework of LMP is written in Shell, we use Python to accelerate some processes. When installing the program, the installer will seach for all Python 3 inside the `$PATH` variable and locate the newest Python as the default Python of the LMP. However, you can modify this by editting the first line of `etc/python.conf` to specific your own Python which should be executable.

== The Documentation Systems

There are multiple documentation format supported. When installing the software by `./install.sh`, you can choose to build specific documentations. All the documentations are generated by `asciidoctor` file located in `INSTALLER/doc` so the documentations generated should be identical.

=== Available Formats

- PDF. This is generated by command `asciidoctor-pdf` and can be found at the folder `pdf`.

- HTML5. This is generated by command `asciidoctor` and can be found at the folder `html`.

- Groff man. This is generated by command `asciidoctor` and can be found at the folder `man`. You can use command `man` to show the contents after restarting your `bash` shell.

- YuZJLab Usage. This is generated by a bash and a Python script located at `INSTALLER` and the documetations are located at folder `doc`. You can use `yldoc` to visit these documents.

=== Using Documentation System

The first few documents to check is `LMP_basis` and `LMP_license`. You can also use the command `yldoc -l` to list all available documentations.

To get help on `yldoc`, just exectue `yldoc -h`.

include::include/copy.adoc[]
