:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= LMP_basis(1)

== NAME

LMP_Basis - The basic configuration of LinuxMiniPrograms.

== SYNOPSIS

yldoc LMP_basis

== DESCRIPTION

This is a descriptional manual; it shows you the basic configuration in LinuxMiniPrograms.

== PYTHON IN LMP

Although the frmework of LMP is written in Shell, we use Python to accelerate some processes. When installing the program, the installer will seach for all Python 3 inside the `$PATH` variable and locate the newest Python as the default Python of the LMP. However, you can modify this by editting the first line of `etc/python.conf` to specific your own Python which should be executable.

== COMPABILITY PROBLEMS

=== GNU/Linux Distributions

Tested and fully supported.

=== BSD

The colouring support of `more` in programs that support `--more:[more]`. Not and will not be fixed. Please use `--more:cat` to get the right colour.

== CYGWin

* There are differences between CYGWin's and Windows' `tar` and `find`. Not and will not be fixed. You need to modify `${PATH}` variable to use CYGWin's biniaries.

* There are differences between CYGWin's and GNU/Linux's `ps`. Fixed.

* Please use CYGWin's Python and Ruby instead of those provided by Conda/Official Python distribution on Windows/Ruby installer.

=== Git Bash

* Lack biniaries in `more`. Not and will not be fixed. Please use `--more:cat` to disable the se of `more`.

* If you install both CYGWin and Git Bash, there woulb be disagree in version of CYGWin.dll. Not and will not be fixed. Can be fixed by uninstalling one of them.

* Python and Ruby may fail. Not and will not be fixed.

=== MSY2

Not tested.

=== Mac

Not tested.

=== Windows Subsystem of Linux

Not tested.

== THE DOCUMENTATION SYSTEMS

There are multiple documentation format supported. When installing the software by `./install.sh`, you can choose to build specific documentations. All the documentations are generated by `asciidoctor` file located in `INSTALLER/doc` so the documentations generated should be identical.

=== Available Formats

* PDF. This is generated by command `asciidoctor-pdf` and can be found at the folder `pdf`.

* HTML5. This is generated by command `asciidoctor` and can be found at the folder `html`.

* Groff man. This is generated by command `asciidoctor` and can be found at the folder `man`. You can use command `man` to show the contents after restarting your `bash` shell.

* YuZJLab Usage. This is generated by a bash and a Python script located at `INSTALLER` and the documetations are located at folder `doc`. You can use `yldoc` to visit these documents.

=== Using Documentation System

The first few documents to check is `LMP_basis` and `LMP_license`. You can also use the command `yldoc -l` to list all available documentations.

To get help on `yldoc` or the format of YuZJLab Usage, just exectue `yldoc -h`.

== DEVELOPING THIS PROJECT

As we're developing programs mostly under Microsoft Windows, we **DO NOT** pay attention to file permissions. You can execute `git config core.filemode false` to make your own copy of repository ignore them as well.

=== Branches on GitHub

There are two main branches on GitHub: `master` and `NEW`. `master` branch is a stable releasing branch and `NEW` branch is cutting-edge developing branch. Other branches should be considered as unstable.

== COMMON ERRORS/WARNINGS

=== `Fail to load libXXX`

After seeing this error, you should check whether this file exists at directory `lib`. If not, you can re-clone the project. If the problem still exists, report this bug to me.

== SEE ALSO

libisopt

include::include/copy.adoc[]
