#!/bin/bash
echo -e "\e[33mYuZJLab Process Snapshot Searcher Usage: pss [string]\e[0m"
echo -e "\e[33mCopyright (C) 2019-2020 YU Zhejian\e[0m"
ps -A all>psstmp
if [ -z $1 ]; then
cat psstmp|more
else
head -n 1 psstmp
grep $1 psstmp --color=auto
fi
rm psstmp
