#!/bin/bash
echo -e "\e[33mYuZJLab Bash History Searcher Usage: bhs [string]\e[0m"
echo -e "\e[33mCopyright (C) 2019-2020 YU Zhejian\e[0m"
HISTFILE=~/.bash_history
set -o history
history|grep --color=auto -- $1
