#!/bin/bash
echo -e "\e[33mYuZJLab Parallel GZIP, a file compression tool. \e[31mWarning: DO NOT USE IT ON COMPUTE CLUSTER."
echo -e "\e[33mCopyright (C) 2019-2020 YU Zhejian\e[0m"
if /usr/bin/parallel -h&>>/dev/null;then
if [ -z $1 ];then
echo -e "\e[31mERROR: No sourcefile. Usage: pgzip [source].\e[0m"
elif [ -f $1 ];then
cat $1|/usr/bin/parallel --pipe --recend '' -k gzip -9 > $1.gz
tmps1=(`du $1`)
tmps2=(`du $1.gz`)
rt=`echo \(${tmps1[0]}-${tmps2[0]}\)\*100/${tmps1[0]}|bc`
echo -e "\e[33mFinished. Size of $1 reduced from ${tmps1[0]} to ${tmps2[0]} by ${rt}%.\e[0m"
else
echo -e "\e[31mInvalid source file '$1'. Usage: pgzip [source].\e[0m"
fi
else
echo -e "\e[31mCANNOT ACCESS GNU PARALLEL. PLEASE MAKE SURE THAT GNU PARALLEL APPEARS IN YOUR /usr/bin\e[0m"
fi
