#!/bin/bash
function DO_ECHO(){
    if ! [ $LIBDO_PRD ];then
        echo $@>>$LIBDO_LOG
    else
        echo -e "\e[33m$@\e[0m"
    fi
}
function DO(){
    if [ -z $LIBDO_LOG ];then
        LIBDO_PRD=true
        elif ! [ -f $LIBDO_LOG ];then
        touch $LIBDO_LOG
    fi
    DO_ECHO "LIBDO IS GOING TO EXECUTE $@ ."
    if ! [ $LIBDO_PRD ]; then
        eval $@ &>>$LIBDO_LOG
    else
        eval $@
    fi
    LIBDO_PRIV=$?
    if [ $LIBDO_PRIV -ne 0 ];then
        DO_ECHO "LIBDO FAILED, GOT \$?=$LIBDO_PRIV."
        if ! [ -z $LIBDO_TOP_PID ];then
            DO_ECHO "WILL KILL $LIBDO_TOP_PID"
            kill -9 $LIBDO_TOP_PID
        fi
    fi
    DO_ECHO "LIBDO EXITED SUCCESSFULLY."
    return $LIBDO_PRIV
}
# Do something! The return value is the exit value of "something".
# ENVIRONMENTAL VARIABLES:
# LIBDO_TOP_PID: the pid to kill if failed. If blank, will not kill.
# LIBDO_PRIV: exit status.
# LIBDO_LOG: log name. If blank, there will be no logs.
# LIBDO_PRD: redierct or pipe is used in the code. If you need redirections, USE ESCAPE (\)!