#!/bin/bash
#libdate V1
function timediff(){
    local Start_Sec=`date --date="${1}" +%s`
    local End_Sec=`date --date="${2}" +%s`
    if [ $Start_Sec -ge $End_Sec ];then
        local Diff_Sec=$[$Start_Sec-$End_Sec]
    else
        local Diff_Sec=$[$End_Sec-$Start_Sec]
    fi
    local Diff_H=$[$Diff_Sec/3600]
    local Diff_M=$[($Diff_Sec-($Diff_H*3600))/60]
    local Diff_S=$[$Diff_Sec%60]
    echo $Diff_H:$Diff_M:$Diff_S
}