#!/bin/bash
# LIBISOPT V1P2
function isopt() {
    case ${1} in
    -? | --* | -?\:* | --*\:*)
        return 0
        ;;
    *)
        return 1
        ;;
    esac
}
# This function can be used to determine whether $1 is an option.
# Examples for option are:
# -h
# --help
# -m:5
# --max:5
