#!/bin/bash
# LIBMKTNL V2
DN=$(dirname ${0})
mypy=$(cat ${DN}/../etc/py)
if [ -x "${mypy}" ];then
    function mktbl() {
        ${mypy} ${DN}/../lib/libmktbl.py "${@}"
    }
else
   . ${DN}/../lib/libmktbl.sh
fi
