#!/usr/bin/env bash
# LIBMAN V1
# TODO: docs
function getuser() {
	if [ -n "${USER:-}" ]; then
		printf "${USER}"
		return
	elif [ -n "${USERNAME:-}" ]; then
		printf "${USERNAME}"
		return
	else
		return 1
	fi
}
function getcorenumber() {
	if [[ ${myos} == *"BSD"* ]]; then
		sysctl -a | grep hw.ncpu | awk '{print $2;}'
	else
		cat /proc/cpuinfo | grep '^processor\s: ' | wc -l | awk '{print $1}'
	fi
}
function killtree() {
    kill -19 ${1} || return
    for CPID in $(ps -o pid --no-headers --ppid ${1}); do
        killtree ${CPID} ${2}
    done
    kill -${2} ${1}
}
