#!/bin/bash
# LIBMKTNL V2P1
DN=$(dirname ${0})
mypy=$(cat ${DN}/../etc/python.conf)
if [ -x "${mypy}" ];then
    function mktbl() {
        ${mypy} ${DN}/../lib/exec/libmktbl.py "${@}"
    }
else
   . ${DN}/../lib/exec/libmktbl.sh
fi
