#!/usr/bin/env bash
# LIBMAN V1
function getuser() {
	if [ -n "${USER:-}" ]; then
		printf "${USER}"
		return
	elif [ -n "${USERNAME:-}" ]; then
		printf "${USERNAME}"
		return
	else
		return 1
	fi
}
function getcorenumber() {
	if [[ ${myos} == *"BSD"* ]]; then
		sysctl -a | grep hw.ncpu | awk '{print $2;}'
	else
		cat /proc/cpuinfo | grep '^processor\s: ' | wc -l | awk '{print $1}'
	fi
}
