#!/usr/bin/env bash
# LIBMAN V1
function getuser() {
	if [ -n "${USER:-}" ] ;then
		printf "${USER}"
		return
	elif [ -n "${USERNAME:-}" ] ;then
		printf "${USERNAME}"
		return
	else
		return 1
	fi
}
function getcorenumber(){
	if [[ ${OS} =~ .*"Linux".* ]];then
		"${mycat}" /proc/cpuinfo | "${mygrep}" '^processor\s: ' | wc -l | awk '{print $1}'
	elif [[ ${OS} =~ .*"BSD".* ]];then
		sysctl -a|grep hw.ncpu|awk '{print $2;}'
	fi
}
