#!/bin/bash
# LIBPB V1
function libpb_init() {
    # $1: TOTAL $2: Val
    local TMPF=$(mktemp -t libpb.XXXXXX)
    local TMPFF=$(mktemp -t libpb.XXXXXX)
    libpb_activate ${TMPF} &
    echo ${!} > "${TMPF}"
    echo ${1} >>"${TMPF}"
    echo ${TMPFF} >>"${TMPF}"
    echo ${2} >>"${TMPFF}"
    echo ${TMPF}
    echo aaa >&2
}
function libpb_set() {
    #$1: File $2: Val
    echo ${2} >>$(tail -n 1 ${1})
}
function libpb_rm() {
    local TMPF=${1}
    kill -9 $(head -n 1 ${TMPF})
    rm -f $(tail -n 1 ${TMPF})
    rm -f ${TMPF}
}
function libpb_activate() {
    local TMPF=${1}
    local TMPFF=$(tail -n 1 ${TMPF})
    local total=$(head -n 2 ${TMPF}|tail -n 1)
    tail -f ${TMPFF}|while read line; do
        val=$((${line}/${total}*100))
        bar=''
        for ((j = 0; j < ${val}; j++)); do
            bar=${bar}'#'
        done
        echo $val>&2
        #printf "[%-100s][%d%%]" "${bar}" "$((${val}/100))" >&2
    done
}
