#!/usr/bin/env bash
# VERSION=2.4
builtin mapfile -t eachpath  < <(builtin echo ${INPATH} | tr ':' '\n' )
valid_path=':'
invalid_path=':'
duplicated_path=':'
for dir in "${eachpath[@]}"; do
    dir_full=$(readlink -f "${dir}" || true)
    if [ ! -d "${dir_full}" ]; then
        invalid_path="${invalid_path}${dir}:"
    elif [[ ${valid_path} == *":${dir_full}:"* ]]; then
        duplicated_path="${duplicated_path}${dir_full}:"
    else
        valid_path="${valid_path}${dir_full}:"
    fi
    builtin unset dir_full dir
done
[ "${duplicated_path}" = ":" ] || duplicated_path=${duplicated_path:1:-1}
[ "${invalid_path}" = ":" ] || invalid_path=${invalid_path:1:-1}
[ "${valid_path}" = ":" ] || valid_path=${valid_path:1:-1}
