#!/bin/bash
# ============ Functions ============
DN=`dirname $0`
if ! [ -f $DN/libautozip ];then
    echo -e "\e[31mERROR: libautozip NO found!.\e[0m"
    exit 1
fi
. $DN/libautozip
# Check filename
function ckfn(){
    if [ ${fn:0-1} = '/' ]; then fn=${fn:0:${#fn}-1};fi
    if [ -z $fn ];then
        autozipck
        exit 0
        elif ! [ -e $fn ];then
        echo -e "\e[31mERROR: Filename '$fn' invalid.\e[0m"
        exit 1
    fi
}
# Check if SPLIT is valid.
function ckSPLIT(){
    if ! $USESPLIT;then return 0;fi
    case $ext in
        "rar")
            if [[ $SPLIT =~ ^[0-9]+[bkm]$ ]] ;then
                echo -e "\e[33mWill split the archive to $SPLIT \e[0m"
                return 0
            fi
        ;;
        "zip")
            if [[ $SPLIT =~ ^[0-9]+[kmgt]$ ]] ;then
                echo -e "\e[33mWill split the archive to $SPLIT \e[0m"
                return 0
            fi
        ;;
        "7z")
            if [[ $SPLIT =~ ^[0-9]+[bkmg]$ ]] ;then
                echo -e "\e[33mWill split the archive to $SPLIT \e[0m"
                return 0
            fi
        ;;
        *)
            if [[ $SPLIT =~ ^[0-9]+$ ]] || [[ $SPLIT =~ ^[0-9]+[KMGTPEZY]$ ]] || [[ $SPLIT =~ ^[0-9]+[KMGTPEZY]B$ ]] ;then
                echo -e "\e[33mWill split the archive to $SPLIT \e[0m"
                return 0
            fi
    esac
    if $USESPLIT;then
        echo -e "\e[31mERROR: SPLIT value '$SPLIT' invalid.\e[0m"
        exit 1
    fi
}
# Check extension names.
function ckext(){
    if [ -z ${STDI[1]} ]; then
        if [ -f $fn ];then
            ext="gz"
        else
            ext="tar.gz"
        fi
    else
        ext=${STDI[1]}
    fi
    case $ext in
        "tar"|"tar.gz"|"tgz"|"tar.GZ"|"tar.xz"|"txz"|"tar.bz2"|"tbz"|"tar.lzma"|"tar.lz"|"tlz")
            if [ -f $fn ];then
                echo -e "\e[31mERROR: You're about to compress FILE '$fn' with extension '$ext', which is designed for compressing FOLDERs.\e[0m"
                exit 1
                elif ! [ $TAR -eq 0 ]; then echo -e "\e[31mERROR: Command TAR \e[31mNO\e[33mt exist!\e[0m";exit 1
            fi
        ;;
        "gz"|"bgz"|"GZ"|"xz"|"bz"|"lzma"|"lz")
            if [ -d $fn ];then
                echo -e "\e[31mERROR: You're about to compress FOLDER '$fn' with extension '$ext', which is designed for compressing SINGLE FILE.\e[0m"
                exit 1
            fi
        ;;
        "7z"|"zip"|"rar")
        ;;
        *)
            echo -e "\e[31mERROR: Extension name '$ext' invalid.\nYou can use 'autozip' to check available method and extension.\e[0m"
            exit 1
    esac
}
# Check compression level
function ckLVL(){
    case $ext in
        "xz"|"tar.xz"|"txz"|"zip"|"lzma"|"tlz"|"tar.lzma")
            lvl_able="[0123456789]"
        ;;
        "rar")
            lvl_able="[012345]"
        ;;
        "7z")
            lvl_able="[013579]"
        ;;
        *)
            lvl_able="[123456789]"
    esac
}
# Backup if exist.
function bupf(){
    if $USESPLIT;then
        if [ -e $fn.$ext.[0-9][0-9][0-9] ];then
            for tfn in $fn.$ext.[0-9][0-9][0-9]; do
                mv -f $tfn $tfn.bak
            done
            elif [ -e $fn.part*.$ext ];then
            for tfn in $fn.part*.$ext; do
                mv -f $tfn $tfn.bak
            done
            elif [ -e $fn.z[0-9][0-9] ];then
            for tfn in $fn.z[0-9][0-9]; do
                mv -f $tfn $tfn.bak
            done
            elif [ -e $fn.$ext ];then
            mv -f $fn.$ext $fn.$ext.bak
        fi
        unset tfn
    else
        if [ -e $fn.$ext ];then
            case $ext in
                "tar"|"7z"|"zip"|"rar")
                    echo -e "\e[31mWARNING: $fn.$ext exists! Will ADD NEW&MODIFIED FILES TO $fn.$ext.\e[0m"
                ;;
                *)
                    echo -e "\e[31mWARNING: $fn.$ext exists! Will rename $fn.$ext as $fn.$ext.bak.\e[0m"
                    mv -f $fn.$ext $fn.$ext.bak
            esac
        fi
    fi
}
# ============ Start ============
echo -e "\e[33mYuZJLab AutoZip.\e[0m"
echo -e "\e[33mCopyright (C) 2019-2020 YU Zhejian\e[0m"
preck
if [ $PARALLEL -eq 0 ];then PP="/usr/bin/parallel";fi
USESPLIT=false
# ============ Possess options ============
for opt in $@;do
    if [ `isopt $opt` -eq 0 ];then
        case $opt in
            "-h"|"--help")
                if [ -f $DN/autozip.Usage ];then
                    cat $DN/autozip.Usage
                    exit 0
                else
                    echo -e "\e[31mERROR: $DN/autozip.Usage not found!\e[0m"
                    exit 1
                fi
            ;;
            "-v"|"--version")
                echo "Version 1.0.0"
            ;;
            "-s"|"--split")
                USESPLIT=true
                SPLIT=1G
            ;;
            -s\:*)
                USESPLIT=true
                SPLIT=${opt:3}
            ;;
            --split\:*)
                USESPLIT=true
                SPLIT=${opt:8}
            ;;
            --force-parallel\:*)
                PP=${opt:17}
                if [ `$PP -h&>>/dev/null;echo $?` -eq 0 ];then
                    USEPARALLEL=true
                    echo -e "\e[33mWill use GNU Parallel in '$PP'.\e[0m"
                else
                    echo -e "\e[31mERROR: GNU Parallel path '$PP' invalid.\e[0m"
                    if [ $PARALLEL -eq 0 ];then PP="/usr/bin/parallel";echo -e "\e[31mERROR: Will use GNU Parallel in /usr/bin/parallel\e[0m";fi
                fi
            ;;
            *)
                echo -e "\e[31mERROR: Option '$opt' invalid.\e[0m"
                exit 1
        esac
        OPT="$OPT $opt"
    else
        STDS="$STDS $opt"
    fi
done
# ============ Possess arguments ============
STDI=($STDS)
fn=${STDI[0]}
ckfn $fn
ckext
ckSPLIT
ckLVL
case ${STDI[2]} in
    $lvl_able)
        LVL="-"${STDI[2]}
        if [ $ext = "7z" ];then LVL="-x=${STDI[2]}";fi
    ;;
    *)
        unset LVL
        echo -e "\e[31mWARNING: Compression level '${STDI[2]}' undefined. You can use $lvl_able for $ext extension. Will use default value provided by corresponding algorism.\e[0m"
esac
echo -e "\e[33mReceived: $0 $fn $ext $lvl $OPT \e[0m"
bupf
# ============ Makt tmpdir ============
tempdir=`mktemp -dt autozip.XXXXXX`
echo -e "\e[33mTEMP directory '$tempdir' made.\e[0m"
# ============ Start Compressing ============
case $ext in
    "tar") # ============ tar ============
        if $USESPLIT;then
            echo -e "\e[33mWill execute: tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $fn.$ext.\e[0m"
            tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $fn.$ext.
        else
            echo -e "\e[33mWill execute: tar uvf $fn.$ext $fn\e[0m"
            tar uvf $fn.$ext $fn
        fi
    ;;
    "tar.gz"|"tgz"|"tar.GZ") # ============ tgz ============
        if ! [ $GZIP -eq 0 ]; then echo -e "\e[31mERROR: GZip NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            if $USEPARALLEL;then
                for tfn in $tempdir/$fn.*;do
                    if [ $PIGZ -eq 0 ];then
                        echo -e "\e[33mWill execute: cat $tfn|pigz $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                        cat $tfn|pigz $LVL>$fn.$ext.${tfn:0-3}
                    else
                        echo -e "\e[33mWill execute: cat $tfn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                        cat $tfn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext.${tfn:0-3}
                    fi
                done
            else
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn| gzip $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn| gzip $LVL>$fn.$ext.${tfn:0-3}
                done
            fi
        else
            if $USEPARALLEL;then
                if [ $PIGZ -eq 0 ];then
                    echo -e "\e[33mWill execute: tar cv $fn|pigz $LVL>$fn.$ext\e[0m"
                    tar cv $fn|pigz $LVL>$fn.$ext
                else
                    echo -e "\e[33mWill execute: tar cv $fn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext\e[0m"
                    tar cv $fn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext
                fi
            else
                echo -e "\e[33mWill execute: tar cv $fn|gzip $LVL>$fn.$ext\e[0m"
                tar cv $fn|gzip $LVL>$fn.$ext
            fi
        fi
    ;;
    "tar.xz"|"txz") # ============ txz ============
        if ! [ $XZIP -eq 0 ]; then echo -e "\e[31mERROR: XZ NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            if $USEPARALLEL;then
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn|xz -T0$LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn|xz -T0$LVL>$fn.$ext.${tfn:0-3}
                done
            else
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn|xz $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn|xz $LVL>$fn.$ext.${tfn:0-3}
                done
            fi
        else
            if $USEPARALLEL;then
                echo -e "\e[33mWill execute: tar cv $fn|xz $LVL>$fn.$ext\e[0m"
                tar cv $fn|xz $LVL>$fn.$ext
            else
                echo -e "\e[33mWill execute: tar cv $fn|xz $LVL>$fn.$ext\e[0m"
                tar cv $fn|xz $LVL>$fn.$ext
            fi
        fi
    ;;
    "tar.bz2"|"tbz") # ============ tbz ============
        if ! [ $BZIP2 -eq 0 ]; then echo -e "\e[31mERROR: BZip2 NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            if $USEPARALLEL;then
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext.${tfn:0-3}
                done
            else
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn| bzip2 $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn| bzip2 $LVL>$fn.$ext.${tfn:0-3}
                done
            fi
        else
            if $USEPARALLEL;then
                echo -e "\e[33mWill execute: tar cv $fn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext\e[0m"
                tar cv $fn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext
            else
                echo -e "\e[33mWill execute: tar cv $fn|bzip2 $LVL>$fn.$ext\e[0m"
                tar cv $fn|bzip2 $LVL>$fn.$ext
            fi
        fi
    ;;
    "tar.lzma"|"tar.lz"|"tlz") # ============ tlz ============
        if ! [ $XZIP -eq 0 ]; then echo -e "\e[31mERROR: XZ NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            if $USEPARALLEL;then
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn|xz -T0 --format=lzma $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn|xz -T0 --format=lzma $LVL>$fn.$ext.${tfn:0-3}
                done
            else
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn| xz -T0 --format=lzma $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn| xz -T0 --format=lzma $LVL>$fn.$ext.${tfn:0-3}
                done
            fi
        else
            if $USEPARALLEL;then
                echo -e "\e[33mWill execute:  tar cv $fn|xz -T0 --format=lzma $LVL >$fn.$ext\e[0m"
                tar cv $fn|xz -T0 --format=lzma $LVL >$fn.$ext
            else
                echo -e "\e[33mWill execute: tar cv $fn|xz --format=lzma $LVL >$fn.$ext\e[0m"
                tar cv $fn|xz --format=lzma $LVL >$fn.$ext
            fi
        fi
    ;;
    "gz"|"GZ") # ============ gz ============
        if ! [ $GZIP -eq 0 ]; then echo -e "\e[31mERROR: GZip NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            if $USEPARALLEL;then
                for tfn in $tempdir/$fn.*;do
                    if [ $PIGZ -eq 0 ];then
                        echo -e "\e[33mWill execute: cat $tfn|pigz $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                        cat $tfn|pigz $LVL>$fn.$ext.${tfn:0-3}
                    else
                        echo -e "\e[33mWill execute: cat $tfn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                        cat $tfn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext.${tfn:0-3}
                    fi
                done
            else
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn| gzip $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn| gzip $LVL>$fn.$ext.${tfn:0-3}
                done
            fi
        else
            if $USEPARALLEL;then
                if [ $PIGZ -eq 0 ];then
                    echo -e "\e[33mWill execute: cat $fn|pigz $LVL>$fn.$ext\e[0m"
                    cat $fn|pigz $LVL>$fn.$ext
                else
                    echo -e "\e[33mWill execute: cat $fn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext\e[0m"
                    cat $fn|$PP --pipe --recend '' -k gzip $LVL>$fn.$ext
                fi
            else
                echo -e "\e[33mWill execute: cat $fn|gzip $LVL>$fn.$ext\e[0m"
                cat $fn|gzip $LVL>$fn.$ext
            fi
        fi
    ;;
    "bgz") # ============ bgz ============
        if ! [ $BGZIP -eq 0 ]; then echo -e "\e[31mERROR: BGZip NO exist!\e[0m";exit 1;fi
        $ext="gz"
        if $USESPLIT;then
            echo -e "\e[33mWill execute: cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            tar cv $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            if $USEPARALLEL;then
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn|$PP --pipe --recend '' -k bgzip $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn|$PP --pipe --recend '' -k bgzip $LVL>$fn.$ext.${tfn:0-3}
                done
            else
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn| bgzip $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn| bgzip $LVL>$fn.$ext.${tfn:0-3}
                done
            fi
        else
            if $USEPARALLEL;then
                echo -e "\e[33mWill execute: cat $fn|$PP --pipe --recend '' -k bgzip $LVL>$fn.$ext\e[0m"
                cat $fn|$PP --pipe --recend '' -k bgzip $LVL>$fn.$ext
            else
                echo -e "\e[33mWill execute: cat $fn|bgzip $LVL>$fn.$ext\e[0m"
                cat $fn|bgzip $LVL>$fn.$ext
            fi
        fi
    ;;
    "xz") # ============ xz ============
        if ! [ $XZIP -eq 0 ]; then echo -e "\e[31mERROR: XZ NO exist!\e[0m";exit 1;fi
        if $USEPARALLEL;then PAR="-T0";fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            for tfn in $tempdir/$fn.*;do
                echo -e "\e[33mWill execute: cat $tfn|xz  $PAR $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                cat $tfn|xz $PAR $LVL>$fn.$ext.${tfn:0-3}
            done
        else
            echo -e "\e[33mWill execute: cat $fn|xz -T0$LVL>$fn.$ext\e[0m"
            cat $fn|xz $PAR $LVL>$fn.$ext
        fi
    ;;
    "bz2") # ============ bz2 ============
        if ! [ $BZIP2 -eq 0 ]; then echo -e "\e[31mERROR: BZip2 NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            if $USEPARALLEL;then
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext.${tfn:0-3}
                done
            else
                for tfn in $tempdir/$fn.*;do
                    echo -e "\e[33mWill execute: cat $tfn| bzip2 $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                    cat $tfn| bzip2 $LVL>$fn.$ext.${tfn:0-3}
                done
            fi
        else
            if $USEPARALLEL;then
                echo -e "\e[33mWill execute: cat $fn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext\e[0m"
                cat $fn|$PP --pipe --recend '' -k bzip2 $LVL>$fn.$ext
            else
                echo -e "\e[33mWill execute: cat $fn|gzip $LVL>$fn.$ext\e[0m"
                cat $fn|bzip2 $LVL>$fn.$ext
            fi
        fi
    ;;
    "lz"|"lzma") # ============ lz ============
        if ! [ $XZIP -eq 0 ]; then echo -e "\e[31mERROR: XZ NO exist!\e[0m";exit 1;fi
        if $USEPARALLEL;then PAR=-T0;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.$ext.\e[0m"
            cat $fn|split -a 3  --numeric-suffixes=001  -b $SPLIT - $tempdir/$fn.
            for tfn in $tempdir/$fn.*;do
                echo -e "\e[33mWill execute: cat $tfn|xz $PAR --format=lzma $LVL>$fn.$ext.${tfn:0-3}\e[0m"
                cat $tfn|xz $PAR --format=lzma $LVL>$fn.$ext.${tfn:0-3}
            done
        else
            echo -e "\e[33mWill execute: cat $fn|xz $PAR --format=lzma $LVL>$fn.$ext\e[0m"
            cat $fn|xz $PAR --format=lzma $LVL>$fn.$ext
            
        fi
    ;;
    "7z") # ============ 7z ============
        if ! [ $Z7 -eq 0 ]; then echo -e "\e[31mERROR: p7zip NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then SPL="-v$SPLIT";fi
        if $USEPARALLEL;then PAR="-mmt0";fi
        echo -e "\e[33mWill execute: 7za $PAR u $fn.$ext $fn $LVL $SPL\e[0m"
        7za $PAR u $fn.$ext $fn $LVL $SPL
    ;;
    "zip") # ============ zip ============
        if ! [ $ZIP -eq 0 ]; then echo -e "\e[31mERROR: zip NO exist!\e[0m";exit 1;fi
        if $USESPLIT;then
            echo -e "\e[33mWill execute: zip -s $SPLIT -r $fn.$ext $fn $LVL\e[0m"
            zip -s $SPLIT -r $fn.$ext $fn $LVL
        else
            echo -e "\e[33mWill execute: zip -r $fn.$ext $fn $LVL\e[0m"
            zip-r $fn.$ext $fn $LVL
        fi
    ;;
    "rar") # ============ rar ============
        if ! [ $RAR -eq 0 ]; then echo -e "\e[31mERROR: rar NO exist!\e[0m";exit 1;fi
        if $USEPARALLEL;then PAR="-mt8";fi
        if $USESPLIT;then SPL="-v$SPLIT";fi
        echo -e "\e[33mWill execute: rar $PAR $SPL a $fn.$ext $fn\e[0m"
        rar $PAR $SPL a $fn.$ext $fn
esac
# ============ Finished ============
echo -e "\e[33mWill execute: rm -rf $tempdir\e[0m"
rm -rf $tempdir
echo -e "\e[33mFinished.\e[0m"
exit 0
