#!/usr/bin/env bash
VERSION=1.5
builtin set -eu
DN="$(readlink -f "$(dirname "${0}")")"
. "${DN}"/../etc/path.conf
. "${DN}"/../shlib/libinclude.sh
__include libisopt
__include libstr
__include libman
touch "${DN}"/../etc/ylsjsd.conf
. "${DN}"/../etc/ylsjsd.conf
if [ -z "${YLSJSD_HOME:-}" ]; then
    warnh "YLSJSD_HOME undefined. Will use ${DN}/../var/ylsjs.d"
    YLSJSD_HOME="${DN}"/../var/ylsjs.d
fi
mkdir -p "${YLSJSD_HOME}"
builtin cd "${YLSJSD_HOME}"
STDS=""
for opt in "${@}"; do
    if isopt "${opt}"; then
        case "${opt}" in
        "-h" | "--help")
            yldoc ylsjs
            builtin exit 0
            ;;
        "-v" | "--version")
            builtin echo ${VERSION}
            builtin exit 0
            ;;
        "-x")
            builtin set -x
            ;;
        esac
    else
        [ "${STDS}" = "" ] && STDS="${opt}"
    fi
done
YLSJSD_HOME_PID=""
YLSJSD_HOME_PID="$(cat ylsjsd.lock 2>/dev/null)" || true
if [ "${STDS:-}" = "start" ]; then
    if [ -z "${YLSJSD_HOME_PID}" ]; then
        bash "${DN}"/exec/ylsjsd_local.sh &
    else
        warnh "ylsjsd already started at ${YLSJSD_HOME_PID}"
    fi
elif [ "${STDS:-}" = "stop" ]; then
    if [ -z "${YLSJSD_HOME_PID}" ]; then
        warnh "ylsjsd not started"
    else
        builtin kill -15 "$(cat ylsjsd.lock 2>/dev/null)" || true
    fi
    rm -f ylsjsd.lock 2>/dev/null
elif [ "${STDS:-}" = "restart" ]; then
    ylsjsd stop
    ylsjsd start
elif [ "${STDS:-}" = "clear" ]; then
    ylsjsd stop
    if [ -n "${YLSJSD_HOME_PID}" ]; then killtree "${YLSJSD_HOME_PID}" 9; fi
    rm -rf * || true
elif [ "${STDS:-}" = "status" ]; then
    cat ylsjsd.lock 2>/dev/null || errh "ylsjsd not started"
else
    errh "Command '${STDS:-}' unknown"
fi
