:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= autozip(1)

== NAME

autozip - An automatic file compression tool.

== SYNOPSIS

`autozip [source] [ext] [level] [options]`

== DESCRIPTION

This program will compress files and folders with extension [ext] to [level].

You can make [level] 1 (fastest) to 9 (best). Some algorithms (e.g. LZMA, Deflate) may support 0 which means to be store only without compression. If [level] is omitted, this program will use default value provided by the algorithm. Some programs like zstd may support value up to 19.

If [ext] is also omitted, this program will use gz (For files) & tar.gz (For folders) by default. If [source] is omitted, this program will check the algorithms installed on your computer and return a list of available extension name. If [source] is set to `-` or `/dev/stdin`, will read from standard input.

== OPTIONS

include::include/cmnopt.adoc[]
* `--force` Remove the target if exists.
* `--remove` Remove [source] if success.
* `-d|--decompress` Will initiate `autounzip` with same arguments.
* `-p[:[thread]]|--parallel[:[thread]]` Use `[thread]` threads when creating the archive. `[thread]` should not be higher than the number of cores installed. If `[thread]` is omitted, will use the number of cores installed.
* `-c|--stdout` Pump what is compressed to standard output. Not supported by some algorithms.

include::include/autozipcmn.adoc[]

== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== Cygwin

Tested with all functions supported.

== SEE ALSO

autounzip, azlist, azcat

include::include/copy.adoc[]
