:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= autounzip(1)

== NAME

autounzip - An automatic file decompression tool.

== SYNOPSIS

`autounzip [SOURCE1] [[SOURCE2]...] [options]`

== DESCRIPTION

Extract `[SOURCE]`. If `[SOURCE]` is omitted, the program will check the algorithms installed on your computer and display a list of available extension name.  If [source] is set to `-` or `/dev/stdin`, will read from standard input.

== OPTIONS

include::include/cmnopt.adoc[]
* `--force` Remove the target if exists.
* `--remove` Remove [sorce] if success.
* `-p[:[thread]]|--parallel[:[thread]]` Use `[thread]` threads when extracting the archive. `[thread]` should not be higher than the number of CPU cores installed. If `[thread]` is omitted, will use the number of CPU cores installed.

include::include/autozipcmn.adoc[]

== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== Cygwin

Tested with all functions supported.

== SEE ALSO

azlist, azcat, autozip

include::include/copy.adoc[]
