:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= enigma(1)

== NAME

enigma - YuZJLab Enigma Codex

== SYNOPSIS

`enigma [OPTIONS]`

== DESCRIPTION

Enigma is used to encrypt files. It reads output stream from `b16c` and encrypt them.

Enigma encrypts files by mapping. Each mapping pattern is called a "cog", and each cog have a starting position.

== OPTIONS

include::include/cmnopt.adoc[]
* `-d` To decode instead of encode.
* `-s:[START_STR]` The starting position. The length of the argument should be the same as the number of option cog.
* `-c:[COG]` The cog number to use.
* `-g|--gengear` Generate a new cog.

== EXAMPLES

These examples are tested under WSL.

`enigma` can be used to transform binary data into texts.

The following script shows that `enigma` will not change the content of the file it reads.

[source]
----
(base) 127 2021-01-20_23-46-24 /home/yuzj
$ cat /bin/ls | sha512sum
b1ecf4268efc8787abe4e56bae77a186d8c6ac3e6a62a1a86226db6c06a59685a06613b3b5e65a11d9e8a79bc929e5eefbdb1d3a0d8c0aead1a9cff8a4a33a3a  -

(base) 0 2021-01-20_23-50-26 /home/yuzj/LinuxMiniPrograms  (BSD)
$ cat /bin/ls | enigma
HPEFEMEGACABABAAAAAAAAAAAAAAAAAAADAADOAAABAAAAAABAGIAAAAAAAAAAAAEAAAAAAAAAAAAAAABIDEACAAAAAAAAAAAAAAAAAAEAAADIAAANAAEAAABPAABOAAAGAAAAAAAEAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAANIACAAAAAAAAAAAANIACAAAAAAAAAAAAAIAAAAAA
[...]

(base) 0 2021-01-20_23-50-37 /home/yuzj/LinuxMiniPrograms  (BSD)
$ cat /bin/ls | enigma | enigma -d | sha512sum
b1ecf4268efc8787abe4e56bae77a186d8c6ac3e6a62a1a86226db6c06a59685a06613b3b5e65a11d9e8a79bc929e5eefbdb1d3a0d8c0aead1a9cff8a4a33a3a  -
----

`enigma` can also be used with `enigma`. The default `enigma` installation accepts `enigma` output only.

Please note that after being coded by `enigma`, the size of the file will grow about 1 times.

== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== Cygwin

Tested with all functions supported.

== SEE ALSO

b16c

include::include/copy.adoc[]
