:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= git-mirror(1)

== NAME

git-mirror - Getting Git-server backed-up.

== SYNOPSIS

`git-mirror [subcommand]`

== DESCRIPTION

Execute `[subcommand]` which will be introduced bellow.

== OPTIONS

include::include/cmnopt.adoc[]

== SUBCOMMANDS

=== add

SYNOPSIS: `git-mirror add [URL]`

Add git repository with URL. URL can be of any following forms:

```
ssh://[user@]host.xz[:port]/path/to/repo.git/
git://host.xz[:port]/path/to/repo.git/
http[s]://host.xz[:port]/path/to/repo.git/
[user@]host.xz:path/to/repo.git/
/path/to/repo.git/
file:///path/to/repo.git/
```

By adding a URL, an UUID will be generated as uniq identification of this git repository.
The repository that your URL pointing to will be mirrored to `${git_mirror_dir}/UUID`.

=== sync

Get all changes and make local/remote repository identical.

=== rmrepo

SYNOPSIS: `git-mirror rmrepo [URL/UUID]`

Remove a repository.

OPTION: `-f` for force removal without confirmation.

=== rmrecord

SYNOPSIS: `git-mirror rmrecord [URL/UUID]`

Remove a repository record.
You may use this when `git-mirror rm` fails.

OPTION: `-f` for force removal without confirmation.

=== log

Show logs.

=== gc

Garbage collection for all repository.

=== lsbranch

SYNOPSIS: `git-mirror lsbranch [URL/UUID]`

Show branches and their last commit of some specific repository.
If `[URL/UUID]` is omitted, will list those of all repository.

=== lock

Complicated.
Introduced below.

==== lock ls

List all locks.

==== lock rm

SYNOPSIS: `git-mirror lock rm [URL/UUID]`

Remove lock from `[URL/UUID]`.
Stop if the process is still running.

OPTION: `-f` for force removal without confirmation.

==== lock rm_sarg

Remove sync.lock, rm.lock, archive.lock and gc.lock.

==== lock add

SYNOPSIS: `git-mirror lock add [URL/UUID]`

Add lock to `[URL/UUID]`.
Can be removed with `git-mirror lock rm`.

OPTION: `-f` for force add without confirmation.

=== ls

List all registered git-mirrors and their UUIDs.

== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== Cygwin

Tested with all functions supported.

== FILES

* `etc/git-mirror.conf` Configuration files.
Detailed instructions are available in the file commented.

* `var/git-mirror.d` The default git-mirror directory.

** `var/git-mirror.d/act.log` Logs of actions performed.

** `var/git-mirror.d/logs/${UUID}` Logs of a specific repo.
Produced during add, sync and gc.

** `var/git-mirror.d/${UUID}` Repositories.

** `var/git-mirror.d/uuidtables.d` Databases containing relationship between UUIDs and repository URLs.

include::include/copy.adoc[]
