:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= libstr(1)

== NAME

libstr - A library containing some string manipulating functions.

== SYNOPSIS

`. /PATH/TO/LIBSTR`

== DESCRIPTION

Firstly, use `. /PATH/TO/LIBSTR` to import `libstr`. (Command `source` is equal to command `.`)

You can then use functions inside!

There are also multiple ANSI-standard colors named `ANSI_*` inside this library.

WARNING: Raw use of ANSI escape characters may cause problems! When the output is not a tty (e.g. redirected to some file), the escape characters will mess up the file and the program handling the file! YuZJLab `libstr` includes function to check whether the output terminal have color support and can avoid that tragedy from happening.

== FUNCTIONS

=== `trimstr [STRING]`

The function `trimstr` is like `str.strip()` in Python 3. It accepts a string as input, and then print it out by removing its leading/following space/tab/etc.

=== `errh [STRING]`

Raise an error. Will display red "ERROR: [STRING]" and exit with value 1.

=== `warnh [STRING]`

Raise a warning. Will display red "WARNING: [STRING]".

=== `infoh [STRING]`

Raise an information. Will display yellow "INFO: [STRING]".

include::include/copy.adoc[]
