:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= livechat(1)

== NAME

livechat - A chatting server

== SYNOPSIS

livechat [USER] [OPTIONS]

== DESCRIPTION

Logon as [USER] and start chatting!

== USAGE

There's no need to register. However, you cannot take `SYSTEM` as your account.

When you start chatting, please use `logout`/`exit`/`quit` or press `Ctrl-C` to exit the chatting room.

You may execute shell commands with the prefix "!". For example, `!ls` will execute `ls` and send the result to the network.

Every time there're people joining or leaving, the account named SYSTEM will announce.

=== On a None-Specific User

* Situation: Multiple users operate one non-specific account for particular jobs, for example, different steps in a bio-informatical project.
You need to set up a secret chatting server.

* Installation: No further installation after executing `configure`.

* Usage: No specific usage.

=== On a Specific User

* Situation: You need to set up a chatting server inside a LAN.

* Installation:

. Add a specific user on your server. e.g. user `chat`

. Modify the `.bashrc` file as follows:

```
echo -e "\033[33mChatting server on LAN ***.\033[0m"
livechat
exit
```

* Usage: On the client, use `ssh chat@server_ip_addr` to access the chatting server.

== OPTIONS

include::include/cmnopt.adoc[]

== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== Cygwin

Tested with all functions supported.

== FILES

. `var/livechat.d/SYSTEM` The file containing all messages.

== SEE ALSO

lcman

include::include/copy.adoc[]
