:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= LMP_basis(1)

== NAME

LMP_Basis - The basic configuration of LinuxMiniPrograms.

== SYNOPSIS

`yldoc LMP_basis`

== DESCRIPTION

This is a description manual; it shows you the basic configuration in LinuxMiniPrograms.

== FOLDER STRUCTURE

All codes and binaries of LinuxMiniProgram are installed in a well-organized order like those specified in FHS.

Following shows a list of all directories which may be useful in this program. Comments added are presented behind `#`.

[source]
----
./.git/ # [DEVELOPER ONLY] Git, a version control system.

./.gitignore # [DEVELOPER ONLY] Another file for Git.

./.idea/ # [DEVELOPER ONLY] Files for JetBrains IDEs.

./.vs/ # [DEVELOPER ONLY] Files for Visual Studio Code.

./BeforeAdd.sh # Files for changing line endings. If you met problems in line endings, this file should be executed.

./bin # Here are the path of BINARIES; That is, what will get exected when you input names of them in a shell.

./bin/exec # Supplementary executable files for those in ./bin/

./doc # Help files in YuZJLab Usage. You may use command yldoc to view these files.

# ./etc/ # Configuratio files.

./html # Help files in HTML. You may use an internet browser to view these files.

./install.sh # The installer you've just used.

./lib # Libraries written in Shell Script which is used by executables in ./bin/ and may be useful in your own program.

./libpy # Python libraries.

./LICENSE.md # The license file.

./man # Help files in Groff Manpages. You may use command man to view these files. [NOT SUPPORTED ON BSD]

./opt # Optional programs.

./pdf # Help files in PDF. You may use a PDF viewer to view these files.

./Readme.md # The Readme.

./src # [DEVELOPER ONLY] Source code.

./TODO # What will happen net.

./var/ # Variable files like logs.
----

== EXECUTABLES USED IN THIS PROGRAM

When installing the program, the installer will search for dependent executables inside the `${PATH}` variable and locate their GNU version as the default program of the LMP. All path information will be recorded in `etc/path.sh`.

== COMPATIBILITY

Although we tried our best to eliminate the experience difference between platforms, compatibility errors still exist. Following is a list of common compatibility problems found in LinuxMiniPrograms, please alert. More compatibility problems specified in each program can be found at corresponding manuals.

WARNING: If ypu spot any problems, please firstly search for the manual of each program and `Readme.md`.

=== GNU/Linux Distributions, including Windows Subsystem of Linux (WSL)

There should be no compatibility problems in this platform because this is what this suite of program designed for.
Tested and fully supported.

=== FreeBSD

* `readlink` needs to support `-f` option. This can be done by installing GNU CoreUtils. No and will not be fixed.

* The `more` program in FreeBSD is actually `less`.
To avoid problems, `cat` will be used by Default in `lcman`.

* We need you to mount `proc` under `proc`.
This can be done by (root privilege ) adding `proc /proc procfs rw 0 0` to `/etc/fstab` and execute `a mount -a` afterwards.

* Other BSD distributions like NetBSD or OpenBSD is not tested. We do not have that much time.

=== CYGWin

* There are differences between CYGWin's and GNU/Linux's `ps`.
Fixed.

* Please use CYGWin's Python and Ruby instead of those provided by Conda/Official Python distribution.
Not fixed, but will be fixed. A way to determine whether this interpreter is compiled under CYGWin or Microsoft Windows is being developed.

=== Git Bash

Git bash is considered a modified version of CYGWin. So only limited support is provided.

* Lack `more`.
Not and will not be fixed.
Please use `--more:cat` to disable `more`.

* If you install both CYGWin and Git Bash, there would be disagreement in a version of `CYGWin.dll`.
Not and will not be fixed.
Can be fixed by uninstalling one of them or, at least, remove `CYGWin.dll` of one distribution from the `${PATH}` environment variable of Windows.
You should not worry about unable to use binaries provided by the distribution. You may specify the ${PATH}` environment variable in the startup script of your shell, like `${HOME}/.bashrc`.

* Python and Ruby may fail.
Not and will not be fixed. Using those compiled under CYGWin will cause incompatibility problems.

=== MSYS2

Tested with severe incompatibilities. Sadly, we will not provide support for such system. If you're interested, please use CYGWin instead.

=== MacOS

Tested with severe incompatibilities. Sadly, we will not provide support for such system now.
The reason of such tragedy is we do not have enough money to buy a Mac, and those provided by Virtual Machines aren't powerful enough.
If you're interested in having LinuxMiniProgram under macOS, you may assist us with a usable machine with macOS installation.

=== Other Interesting UNIX-Like Operating Systems

Not tested with unknown level of support.
We would also like to provide support to other interesting UNIX-Like operating systems like MINIX or AIX, but we same as the reason for not supporting macOS, we lack usable hardware that may match those operating systems.

However, as you may see the support information in FreeBSD, differences still exist when talking about UNIX-Like operating systems, especially those early ones. So use with care.

== THE DOCUMENTATION SYSTEMS FOR USERS

All documentation for user is written in Asciidoc except the help file of `install.sh`, or some programs located under `opt/`.

There are multiple documentation format supported.
When installing the software by `./install.sh`, you can choose to build specific formats.

For most programs in `bin/`, you can also use `program --help` to read manual.

=== Available Formats

* Asciidoctor. The source format to generate formats below.

* PDF.

* HTML5.

* Groff man.
This is generated by command `asciidoctor` and can be found at the folder `man`.
You can use command `man` to show the contents after restarting your `bash` shell.
Please notice that BSD `man` may not support customized `${MANPATH}`.

* YuZJLab Usage.
This is generated by a Python script located at `src/exec`, and the documentations are located at the folder `doc`.
You can use `yldoc` to visit these documents.

=== Using Documentation System

The first documents to check is `LMP_basis` and `LMP_license`. It specifies the basic configuration of the LinuxMiniPrograms and what you should pay attention to if you like to share it with your friends. You can also use the command `yldoc -l` to list all available documentations.

Please read the documentation *BEFORE* using a software, otherwise you may experience data loss.

To get help on `yldoc` or the format of YuZJLab Usage, just execute `yldoc -h`.

== DEVELOPING

We are very glad to have you assist us in developing this software! Any help will be welcomed.

=== Git as a Version Control System

As we're developing programs mostly under Microsoft Windows, we **DO NOT** pay attention to file permissions.
You can execute `git config core.filemode false` to make your own copy of repository ignore them as well.

==== Branches on GitHub

There are two main branches on GitHub: `master` and `testing`. `master` branch is a stable releasing branch and `testing` branch is cutting-edge developing branch.
Other branches (e.g. `BSD`) should be considered as unstable.

=== Documentations for Developers

Developers should pay attention to the `Readme.adoc` under each folder and news in `src/news`. All documentations for developers are written in Asciidoc instead of Markdown due to its excellent extensibility. No complex syntax are used in the documentations and should be considered easy to understand by most readers with the experience of writing Markdown.

To convert documentations from Asciidoc to the format you wish, you may use `asciidoc` or `asciidoctor`. Due to some incompatibility problems, using `pandoc` is not recommended.

== UPGRADE

Here are the instructions on how to upgrade LinuxMiniPrograms.

. Use `git pull` to pull down the newest version.

. Use `./installer.sh` to re-generate `etc/path.sh`.
You may also re-compile the documentations.

== SEE ALSO

libisopt, yldoc

include::include/copy.adoc[]
