:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= LMP_basis(1)

== NAME

LMP_Basis - The basic configuration of LinuxMiniPrograms.

== SYNOPSIS

`yldoc LMP_basis`

== DESCRIPTION

This is a descriptional manual; it shows you the basic configuration in LinuxMiniPrograms.

== EXECUTABLES

When installing the program, the installer will seach for dependent executables inside the `$PATH` variable and locate thir GNU version as the default program of the LMP. All path information will be recorded in `etc/path.sh`.

== PYTHON IN LMP

Although the frmework of LMP is written in Shell, we use Python to accelerate some processes.
When installing the program, the installer will seach for all Python 3 inside the `$PATH` variable and locate the newest Python as the default Python of the LMP. However, you can modify this by editting `etc/path.sh` to specific your own Python.

WARNING: For those wo use Windows, please use `python3` in CygWin & MSY2. Using those provided by `conda`, Windows Store or its official installer is *NOT* recommended.

== COMPABILITY

WARNING: If ypu spot any problems, please firstly search for manual and `Readme.md`.

=== GNU/Linux Distributions. including Windows Subsystem of Linux (WSL)

Tested and fully supported.

=== BSD

* The `more` program in FreeBSD is actually `less`.
To avoid problems, `cat` will be used by fefault in `lcman`.

* The `split` program in FreeBSD is incompatiable with GNU `split`.
Please install GNU CoreUtils if you want to use the splitting function in `autozip`.

* We need you to mount `proc` under `proc`.
This can be done by (root privilege ) adding `proc /proc procfs rw 0 0` to `/etc/fstab` and execute `mount -a` afterwards.

=== CYGWin

* There are differences between CYGWin's and GNU/Linux's `ps`.
Fixed.

* Please use CYGWin's Python and Ruby instead of those provided by Conda/Official Python distribution.

=== Git Bash

* Lack `more`.
Not and will not be fixed.
Please use `--more:cat` to disable `more`.

* If you install both CYGWin and Git Bash, there would be disagreement in version of `CYGWin.dll`.
Not and will not be fixed.
Can be fixed by uninstalling one of them or, at least remove from the `$PATH` envoironment variable of Windows,

* Python and Ruby may fail.
Not and will not be fixed.

=== MSY2

Tested. Sadly, we will not provide support for such system. If're interested, please use CYGWin instead.

=== MacOS

Tested. Sadly, we will not provide support for such system.

== THE DOCUMENTATION SYSTEMS

There are multiple documentation format supported.
When installing the software by `./install.sh`, you can choose to build specific formats.
All documentations are generated by `asciidoctor` file located in `src/doc`.

You can also use `program --help` to read manual.

=== Available Formats

* PDF. This is generated by command `asciidoctor-pdf` and can be found at the folder `pdf`.

* HTML5. This is generated by command `asciidoctor` and can be found at the folder `html`.

* Groff man.
This is generated by command `asciidoctor` and can be found at the folder `man`.
You can use command `man` to show the contents after restarting your `bash` shell.

* YuZJLab Usage.
This is generated by a bash and a Python script located at `src/exec` and the documetations are located at folder `doc`.
You can use `yldoc` to visit these documents.

=== Using Documentation System

The first documents to check is `LMP_basis` and `LMP_license`.
You can also use the command `yldoc -l` to list all available documentations.

To get help on `yldoc` or the format of YuZJLab Usage, just exectue `yldoc -h`.

== DEVELOPING

As we're developing programs mostly under Microsoft Windows, we **DO NOT** pay attention to file permissions.
You can execute `git config core.filemode false` to make your own copy of repository ignore them as well.

=== Branches on GitHub

There are two main branches on GitHub: `master` and `testing`. `master` branch is a stable releasing branch and `testing` branch is cutting-edge developing branch.
Other branches should be considered as unstable.

== UPGRADE

Here are the instructions on how to upgrade LinuxMiniPrograms.

. Use `git pull` to pull down the newest version.

. Use `./installer.sh --update` to re-generate `etc/path.sh`.
You may also re-compile the documentations.

== SEE ALSO

libisopt

include::include/copy.adoc[]
