:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= ylsjs(1)

== NAME

ylsjs - YuZJLab Simple Job Server.

== SYNOPSIS

`ylsjs [SUBCOMMAND]`

== DESCRIPTION

ylsjs is the frontend of ylsjsd, includes common tasks like job creation (`init`), removal (`kill`) and status-checking (`ps`).

For [SUBCOMMAND] in `start` `stop` `restart` `clear` `status`, please refer to the documentation of ylsjsd.

== SUBCOMMANDS

=== init

Start a job by pumping its script to /dev/stdin.

Options:

* `-n:|--name:[NAME]` Set the job name displayed. Default will be `UK`.

=== bsub

To init a job using grmmar of IBM LSF Systems. Options may be specified by `# BSUB [OPTION]` inside the script.

=== ps

To print jobs.

Options:

* `--pid-only` Get the top process ids.
* `--id-only` To show all running id.
* `-V` Verbose format. The following options is only available with `-V` on:
** `-p|--pst` Use pstree to display process information.
** `-t|--top` Use top to display process information.
** `-s:--show-sh` To show the shell script passed in.
** `--stdout` To show standard output.
** `--stderr` To show standard error.
** `-env` Show environment variables when exected.

=== kill

To kill jobs by its number.

Options:

* `-n:[SIGNAL_NUMBER]` Send signal [SIGNAL_NUMBER] to the job. For example, use 9 to force kill a progress.

== OPTIONS

include::../include/cmnopt.adoc[]

== EXAMPLES

[source]
----
0 2021-03-11_14-09-21 /mnt/d/Work/LinuxMiniPrograms  (BSD)
$ echo "sleep 1000"|ylsjs init -n:sleep
ls: cannot access '*.sh': No such file or directory
1
sleep
0 2021-03-11_14-09-43 /mnt/d/Work/LinuxMiniPrograms  (BSD)
$ ylsjs ps
|===============================|
|NO.|NAME |PID  |EXECTIME|STATUS|
|===============================|
|1  |sleep|16491|0:0:14  |EXEC  |
|===============================|
0 2021-03-11_14-10-09 /mnt/d/Work/LinuxMiniPrograms  (BSD)
$ ylsjs ps -V -a -t -p
# ---------------No=1,  NAME=sleep,     PID=16491,      STATUS=EXEC---------------
    # ---------------pstree 1---------------
bash,16491 /mnt/d/Work/LinuxMiniPrograms/bin/exec/../../var/ylsjs.d/1.sh
  └─sleep,16493 1000
    # ---------------top 1---------------
top - 14:10:12 up 1 day,  1:18,  0 users,  load average: 0.10, 0.10, 0.07
Threads:   1 total,   0 running,   1 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   9362.9 total,   7890.1 free,    187.1 used,   1285.7 buff/cache
MiB Swap:   3072.0 total,   3072.0 free,      0.0 used.   8940.6 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
16491 yuzj      20   0    8824   3264   3040 S   0.0   0.0   0:00.00 bash /mnt/d/Work/LinuxMiniPrograms/bin/exec/../../var/ylsjs.d/1.sh
0 2021-03-11_14-10-12 /mnt/d/Work/LinuxMiniPrograms  (BSD)
$ ylsjs kill 1
WARNING: Failed to kill 1 with PID=16491. Retry with -n:9 option
0 2021-03-11_14-10-27 /mnt/d/Work/LinuxMiniPrograms  (BSD)
$ ylsjs kill 1 -n:9
/mnt/d/Work/LinuxMiniPrograms/bin/exec/ylsjsd.sh: line 44: 16491 Killed                  bash "${YLSJSD_HOME}"/${lastq}.sh > "${YLSJSD_HOME}"/${lastq}.stdout 2> "${YLSJSD_HOME}"/${lastq}.stderr  (wd: /mnt/d/Work/LinuxMiniPrograms)
1 killed
0 2021-03-11_14-10-34 /mnt/d/Work/LinuxMiniPrograms  (BSD)
$ ylsjs ps
|===============================|
|NO.|NAME |PID  |EXECTIME|STATUS|
|===============================|
|1  |sleep|16491|0:0:52  |DONE  |
|===============================|
----

== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== Cygwin

Tested with all functions supported.

== FILES

== SEE ALSO

ylsjsd

include::../include/copy.adoc[]
