== NOTES

=== USE OF PIGZ

When `pigz` and GNU parallel both exist and you have `PARALLEL` in `autozip.conf`, `pigz` will be used.

=== USE OF GZIP

When processing bioinformatical data, please make sure that You should use GZIP to produce a _GZIP COMPRESSED DATA_ instead of BGZIP to produce a _BLOCKED GNU ZIP FORMAT_ before using this tool!

=== USE OF BGZIP

This is the right way to produce a _BLOCKED GNU ZIP FORMAT_ with `gz` extension. Because it is capable of GNU GZip, we'll not distinguish them when extracting data. `tar.gz` is not supported in bgz format because it sounds weird.

=== USE OF LZMA SDK AND XZ UTILS

The core of the XZ Utils compression code is based on LZMA SDK. So when you're about to compress & decompress files with `lz`, `lzma`, `tar.lz`,`tar.lzma`, `tlz` extensions, we'll use XZ Utils.

=== USE OF 7ZIP

WARNING: DO NOT USE the 7-zip format for backup purpose on Unix-Like operating systems because 7-zip does not store the owner/group of the file.

WARNING: Although 7-zip provided us with a handful of algorithms, we will only take default values.

=== USE OF RAR

WARNING: RAR is a _PROPERTY_ software.

== CONFIGURATION

The configuration file of program `autozip` is `etc/autozip.conf`. There should be one line inside the file. If there're multiple lines, the lines behind will be ignored.

`PARALLEL` or `NOPARALLEL` (default) at line 1 indicates whether or not to use GNU Parallel.

== EXAMPLE

These examples are tested under CYGWin.

The following example is the checking step:

```
admin@DESKTOP-FFEV0AF /d/Software/LinuxMiniPrograms
$ autounzip
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoUnZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
Start checking all compoments...
Checking for 'tar'...OK
Checking for 'gzip'...OK
Checking for 'pigz'...OK
Checking for 'bgzip'...NO
Checking for 'xz'...OK
Checking for 'bzip2'...OK
Checking for '7z'...OK
Checking for 'zip'...OK
Checking for 'rar'...OK
Checking for 'unzip'...OK
Checking for 'unrar'...OK
Checking for 'parallel' in /usr/bin...OK
Available extension name on your computer:
tar, gz, GZ, tar.gz, tar.GZ, tgz, xz, lzma, lz, tar.xz, txz, tar.lzma, tlz, bz2, tar.bz2, tbz, 7z, zip, rar
```

The following example is to archive folder `R` with all default settings and an existing archive:

```
admin@DESKTOP-FFEV0AF ~
$ autozip R
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
WARNING: Compression level '' undefined. You can use [123456789] for tar.gz extension. Will use default value provided by corresponding algorism.
Received: /d/Software/LinuxMiniPrograms/bin/autozip R tar.gz
WARNING: R.tar.gz exists! Will rename R.tar.gz as R.tar.gz.bak.
a R
a R/win-library
a R/win-library/3.6
Removing temporary resources...
Finished.
```

The following command is how we investigate the archive made in the previous step:

```
admin@DESKTOP-FFEV0AF ~
$ azman list R.tar.gz
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoZipManager
Copyright (C) 2020 YU Zhejian
Will use GNU Parallel if possible.
Received: /d/Software/LinuxMiniPrograms/bin/azman list R.tar.gz  ==>Extension=tar.gz
drwxrwxrwx  0 0      0           0 4? 24 21:21 R/
drwxrwxrwx  0 0      0           0 4? 24 21:21 R/win-library/
drwxrwxrwx  0 0      0           0 4? 24 21:21 R/win-library/3.6/
Finished.
```

The following command is how we extract this archive. This command also removes pre-exist folder `R` and `R.tar.gz` if success.

```
admin@DESKTOP-FFEV0AF ~/a
$ autounzip R.tar.gz --remove --force
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoUnZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
WARNING: Will remove  if success.
Received: /d/Software/LinuxMiniPrograms/bin/autounzip R.tar.gz  --remove --force ==>Extension=tar.gz
WARNING: R exists! Will remove R.
R
R/win-library
R/win-library/3.6
Removing temporary resources...
Finished.
```

Splitting archive:

```
admin@DESKTOP-FFEV0AF ~/a
$ autozip Desktop txz -s:10M
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
Will split the archive to 10M
WARNING: Compression level '' undefined. You can use [0123456789] for txz extension. Will use default value provided by corresponding algorism.
Received: /d/Software/LinuxMiniPrograms/bin/autozip Desktop txz   -s:10M
WARNING: Desktop.txz exists! Will rename Desktop.txz as Desktop.txz.bak.
TEMP file '/tmp/autozip.Z9aUgI' and directory '/tmp/autozip.FsjMHB' made.
LIBDO IS GOING TO EXECUTE tar -f - -cv Desktop|split -a 3 --numeric-suffixes=001 -b 10M - /tmp/autozip.FsjMHB/Desktop.
Desktop/
Desktop/1.reg.xz
[..]
Desktop/[Tim Hall, J-P Stacey ] Python3 For Absolute Beginners.pdf
Desktop/\346\220\234\347\264\242 Everything.lnk
Removing temporary resources...
Finished.
```

```
admin@DESKTOP-FFEV0AF ~/a
$ autounzip Desktop.txz
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoUnZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
Received: /d/Software/LinuxMiniPrograms/bin/autounzip Desktop.txz  ==>Extension=txz
TEMP file '/tmp/autozip.PV6RNx' and directory '/tmp/autozip.Ibs37M' made.
Desktop/
Desktop/1.reg.xz
[..]
Desktop/[Tim Hall, J-P Stacey ] Python3 For Absolute Beginners.pdf
Desktop/\346\220\234\347\264\242 Everything.lnk
Removing temporary resources...
Finished.
```
== FILES
. `etc/autozip.conf` The main condiguration file of this program.
