== NOTES

=== USE OF GNU PARALLEL (REQUIRE ROOT PREVILEDGE)

It is recommended to use GNU Parallel to accelerate the speed of compression. You can change the first line of autozip.conf to "PARALLEL" to enable this feature. GNU Parallel is not available on autounzip.

When using XZ Utils, we will use argument "-T0" instead of GNU Parallel.
    
WARNING: GNU Parallel consumes lots of memory & CPU resources. NEVER USE IT ON CLUSTERS!!!

=== USE OF PIGZ

When pigz, GNU parallel both exist and you have PARALLEL in autozip.conf, pigz will be used.

=== USE OF GNU GZIP

When processing bioinformatical data, please make sure that You should use GZIP to produce a GZIP COMPRESSED DATA instead of BGZIP to produce a BLOCKED GNU ZIP FORMAT before using this tool!

=== USE OF BGZIP

This is the right way to produce a BLOCKED GNU ZIP FORMAT with "gz" extension. Because it is capable of GNU GZip, we'll not distinguish them when extracting data. "tar.gz" is not supported in bgz format because it sounds weird.

=== USE OF LZMA SDK AND XZ UTILS

The core of the XZ Utils compression code is based on LZMA SDK. So when you're about to compress & decompress files with lz, lzma, tar.lzma, tlz extensions, we'll use XZ Utils.

=== USE OF 7ZIP

WARNING: DO NOT USE the 7-zip format for backup purpose on Linux/Unix because 7-zip does not store the owner/group of the file.

WARNING: Although 7-zip provided us with a handful of algorithms, we will only take default values.

=== USE OF RAR

WARNING: 1. RAR is a PROPERTY software. 2. Use ABSOLUTE PATH.

== CONFIGURATION

The configuration file of `autozip` and `autounzip` is `etc/autozip.conf`. There should be one line inside the file. If there're multiple lines, the lines behind line 1 will be ignored.

- `PARALLEL` or `NOPARALLEL` (default) at line 1 indicates whether or not to use GNU Parallel. If you want to ise GNU Parallel, you should change line 1 to `PARALLEL`.

== FILES

- `etc/autozip.conf`: The configuration file of `autozip` and `autounzip`.

== EXAMPLE

These examples are tested under CYGWin.

The following example is the checking step:

```
admin@DESKTOP-FFEV0AF /d/Software/LinuxMiniPrograms
$ autounzip
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoUnZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
Start checking all compoments...
Checking for 'tar'...OK
Checking for 'gzip'...OK
Checking for 'pigz'...OK
Checking for 'bgzip'...NO
Checking for 'xz'...OK
Checking for 'bzip2'...OK
Checking for '7z'...OK
Checking for 'zip'...OK
Checking for 'rar'...OK
Checking for 'unzip'...OK
Checking for 'unrar'...OK
Checking for 'parallel' in /usr/bin...OK
Available extension name on your computer:
tar, gz, GZ, tar.gz, tar.GZ, tgz, xz, lzma, lz, tar.xz, txz, tar.lzma, tlz, bz2, tar.bz2, tbz, 7z, zip, rar
Configure file /d/Software/LinuxMiniPrograms/bin/../etc/autozip.conf are as follows:
=====Begin /d/Software/LinuxMiniPrograms/bin/../etc/autozip.conf=====
PARALLEL

=====End   /d/Software/LinuxMiniPrograms/bin/../etc/autozip.conf=====
```

The following example is to archive folder `R` with all default settings and an existing archive:

```
admin@DESKTOP-FFEV0AF ~
$ autozip R
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
WARNING: Compression level '' undefined. You can use [123456789] for tar.gz extension. Will use default value provided by corresponding algorism.
Received: /d/Software/LinuxMiniPrograms/bin/autozip R tar.gz
WARNING: R.tar.gz exists! Will rename R.tar.gz as R.tar.gz.bak.
LIBDO IS GOING TO EXECUTE mv -f R.tar.gz R.tar.gz.bak
LIBDO STARTED AT Sat May  2 14:36:58     2020.
LIBDO PID 1805 with top_pid 1785
LIBDO STOPPED AT Sat May  2 14:36:58     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE tar -f - -cv R|pigz >R.tar.gz
LIBDO STARTED AT Sat May  2 14:36:58     2020.
LIBDO PID 1813 with top_pid 1785
a R
a R/win-library
a R/win-library/3.6
LIBDO STOPPED AT Sat May  2 14:36:59     2020.
LIBDO EXITED SUCCESSFULLY.
Removing temporary resources...
Finished.
```

The following command is how we investigate the archive made in the previous step:

```
admin@DESKTOP-FFEV0AF ~
$ azman list R.tar.gz
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoZipManager
Copyright (C) 2020 YU Zhejian
Will use GNU Parallel if possible.
Received: /d/Software/LinuxMiniPrograms/bin/azman list R.tar.gz  ==>Extension=tar.gz
drwxrwxrwx  0 0      0           0 4? 24 21:21 R/
drwxrwxrwx  0 0      0           0 4? 24 21:21 R/win-library/
drwxrwxrwx  0 0      0           0 4? 24 21:21 R/win-library/3.6/
Finished.
```

The following command is how we extract this archive. This command also removes pre-exist folder `R` and `R.tar.gz` if success.

```
admin@DESKTOP-FFEV0AF ~/a
$ autounzip R.tar.gz --remove --force
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoUnZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
WARNING: Will remove  if success.
Received: /d/Software/LinuxMiniPrograms/bin/autounzip R.tar.gz  --remove --force ==>Extension=tar.gz
WARNING: R exists! Will remove R.
LIBDO IS GOING TO EXECUTE rm -rf R
LIBDO STARTED AT Sat May  2 15:00:23     2020.
LIBDO PID 2127 with top_pid 2109
LIBDO STOPPED AT Sat May  2 15:00:24     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE tar xzvf R.tar.gz
LIBDO STARTED AT Sat May  2 15:00:24     2020.
LIBDO PID 2135 with top_pid 2109
R
R/win-library
R/win-library/3.6
LIBDO STOPPED AT Sat May  2 15:00:25     2020.
LIBDO EXITED SUCCESSFULLY.
Removing temporary resources...
LIBDO IS GOING TO EXECUTE rm -rf R.tar.gz
LIBDO STARTED AT Sat May  2 15:00:25     2020.
LIBDO PID 2140 with top_pid 2109
LIBDO STOPPED AT Sat May  2 15:00:25     2020.
LIBDO EXITED SUCCESSFULLY.
Finished.
```

Splitting archive:

```
admin@DESKTOP-FFEV0AF ~/a
$ autozip Desktop txz -s:10M
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
Will split the archive to 10M
WARNING: Compression level '' undefined. You can use [0123456789] for txz extension. Will use default value provided by corresponding algorism.
Received: /d/Software/LinuxMiniPrograms/bin/autozip Desktop txz   -s:10M
WARNING: Desktop.txz exists! Will rename Desktop.txz as Desktop.txz.bak.
TEMP file '/tmp/autozip.Z9aUgI' and directory '/tmp/autozip.FsjMHB' made.
LIBDO IS GOING TO EXECUTE tar -f - -cv Desktop|split -a 3 --numeric-suffixes=001 -b 10M - /tmp/autozip.FsjMHB/Desktop.
LIBDO STARTED AT Sat May  2 15:06:25     2020.
LIBDO PID 2172 with top_pid 2148
Desktop/
Desktop/1.reg.xz
[..]
Desktop/[Tim Hall, J-P Stacey ] Python3 For Absolute Beginners.pdf
Desktop/\346\220\234\347\264\242 Everything.lnk
LIBDO STOPPED AT Sat May  2 15:06:25     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.FsjMHB/Desktop.001|xz --threads=0 >Desktop.txz.001
LIBDO STARTED AT Sat May  2 15:06:25     2020.
LIBDO PID 2177 with top_pid 2148
LIBDO STOPPED AT Sat May  2 15:06:30     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.FsjMHB/Desktop.002|xz --threads=0 >Desktop.txz.002
LIBDO STARTED AT Sat May  2 15:06:30     2020.
LIBDO PID 2182 with top_pid 2148
LIBDO STOPPED AT Sat May  2 15:06:33     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.FsjMHB/Desktop.003|xz --threads=0 >Desktop.txz.003
LIBDO STARTED AT Sat May  2 15:06:33     2020.
LIBDO PID 2187 with top_pid 2148
LIBDO STOPPED AT Sat May  2 15:06:37     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.FsjMHB/Desktop.004|xz --threads=0 >Desktop.txz.004
LIBDO STARTED AT Sat May  2 15:06:37     2020.
LIBDO PID 2192 with top_pid 2148
LIBDO STOPPED AT Sat May  2 15:06:39     2020.
LIBDO EXITED SUCCESSFULLY.
Removing temporary resources...
Finished.
```

```
admin@DESKTOP-FFEV0AF ~/a
$ autounzip Desktop.txz
libisopt, libdo loaded.
libautozip loaded.
YuZJLab AutoUnZip
Copyright (C) 2019-2020 YU Zhejian
Will use GNU Parallel if possible.
Received: /d/Software/LinuxMiniPrograms/bin/autounzip Desktop.txz  ==>Extension=txz
TEMP file '/tmp/autozip.PV6RNx' and directory '/tmp/autozip.Ibs37M' made.
Will execute: echo "cat /c/Users/admin/a/Desktop.txz.001|xz -dk>>/tmp/autozip.Ibs37M/001">>/tmp/autozip.Ibs37M/001.sh
Will execute: echo "cat /c/Users/admin/a/Desktop.txz.002|xz -dk>>/tmp/autozip.Ibs37M/002">>/tmp/autozip.Ibs37M/002.sh
Will execute: echo "cat /c/Users/admin/a/Desktop.txz.003|xz -dk>>/tmp/autozip.Ibs37M/003">>/tmp/autozip.Ibs37M/003.sh
Will execute: echo "cat /c/Users/admin/a/Desktop.txz.004|xz -dk>>/tmp/autozip.Ibs37M/004">>/tmp/autozip.Ibs37M/004.sh
LIBDO IS GOING TO EXECUTE find /tmp/autozip.Ibs37M/*.sh|/usr/bin/parallel bash
LIBDO STARTED AT Sat May  2 15:12:54     2020.
LIBDO PID 2402 with top_pid 2372
LIBDO STOPPED AT Sat May  2 15:12:58     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.Ibs37M/001>>/tmp/autozip.PV6RNx
LIBDO STARTED AT Sat May  2 15:12:58     2020.
LIBDO PID 2429 with top_pid 2372
LIBDO STOPPED AT Sat May  2 15:12:58     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.Ibs37M/002>>/tmp/autozip.PV6RNx
LIBDO STARTED AT Sat May  2 15:12:58     2020.
LIBDO PID 2434 with top_pid 2372
LIBDO STOPPED AT Sat May  2 15:12:58     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.Ibs37M/003>>/tmp/autozip.PV6RNx
LIBDO STARTED AT Sat May  2 15:12:58     2020.
LIBDO PID 2439 with top_pid 2372
LIBDO STOPPED AT Sat May  2 15:12:58     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE cat /tmp/autozip.Ibs37M/004>>/tmp/autozip.PV6RNx
LIBDO STARTED AT Sat May  2 15:12:58     2020.
LIBDO PID 2444 with top_pid 2372
LIBDO STOPPED AT Sat May  2 15:12:59     2020.
LIBDO EXITED SUCCESSFULLY.
LIBDO IS GOING TO EXECUTE tar xvf /tmp/autozip.PV6RNx
LIBDO STARTED AT Sat May  2 15:12:59     2020.
LIBDO PID 2449 with top_pid 2372
Desktop/
Desktop/1.reg.xz
[..]
Desktop/[Tim Hall, J-P Stacey ] Python3 For Absolute Beginners.pdf
Desktop/\346\220\234\347\264\242 Everything.lnk
LIBDO STOPPED AT Sat May  2 15:13:00     2020.
LIBDO EXITED SUCCESSFULLY.
Removing temporary resources...
Finished.
```
