:toc:
:author: YU Zhejian [Zhejian.19@intl.zju.edu.cn]

= git-mirror(1)

== NAME

git-mirror - Getting Git-server backed-up.

== SYNOPSIS

`git-mirror [subcommand]`

WARNING: This program is no longer monitored and updates may not be provided

== DESCRIPTION

Execute `[subcommand]` which will be introduced bellow.

== OPTIONS

include::include/cmnopt.adoc[]

== SUBCOMMANDS

To view descriptons of each sub command, refer to documetation named `git-mirror_[SUBCOMMANDS]`.

add, gc, lock, log, ls, lsbranch, rmrecord, rmrepo, sync

=== gc


== COMPATIBILITY

=== BSD

Tested with all functions supported.

=== Cygwin

Tested with all functions supported.

== FILES

* `etc/git-mirror.conf` Configuration files. Detailed instructions are available in the file commented.
* `var/git-mirror.d` The default git-mirror directory.
** `var/git-mirror.d/act.log` Logs of actions performed.
** `var/git-mirror.d/logs/${UUID}` Logs of a specific repo. Produced during `add`, `sync` and `gc`.
** `var/git-mirror.d/${UUID}` Repositories.
** `var/git-mirror.d/uuidtables.d` Databases containing relationship between UUIDs and repository URLs.

== KNOWN BUGS

URL with one longer than another with same leading digits may fail.

Example: http://git.a.com/a and http://git.a.com/aas

include::include/copy.adoc[]
