#!/bin/bash
# AD2U V1P5
DN=$(dirname ${0})

function getfullasciidoc() {
    while read line; do
        if [[ ${line} =~ include::.*\[\] ]]; then
            local deepfn=$(echo ${line} | sed "s/^include\:\://" | sed "s/\[\]$//")
            getfullasciidoc ${DN}/doc/${deepfn}
        else
            echo ${line}
        fi
    done <"${1}"
}

pypath=$(cat ${DN}/../etc/python.conf)
if [ -z ${pypath} ];then
    exit 1
fi
rm -f ./*.im ../doc/*.usage
for fn in ${DN}/doc/*.adoc; do
    fn_base=$(basename ${fn%.*})
    getfullasciidoc ${fn} | sed 's/^==*/#/' | sed 's/^\:.*\:.*$//' |grep -v '^#.*([0-9])$'|grep -v '^image::'| grep -v '^$' >${fn_base}.im
    ${pypath} adoc2usage_phase2.py ${fn_base}.im
    if [ ${?} -eq 0 ];then
        echo -e "\e[33mCompiling ${fn_base} in YuZJLab Usage...\e[32mPASSED\e[0m"
    else
        echo -e "\e[33mCompiling ${fn_base} in YuZJLab Usage...\e[31mERROR\e[0m"
    fi
done
rm -f ./*.im ../doc/*.usage
mv *.usage ../doc/
