#!/bin/bash
# CONFIGPY V1
DN=$(dirname ${0})
echo -e "\e[33mConfiguring Python...\e[0m"
. ${DN}/../lib/libfindpython && echo -e "\e[33mlibfindpython loaded.\e[0m" || {
    echo -e "\e[31mFail to load libfindpython.\e[0m"
    exit 1
}
n=0

FindPython 3 > ${DN}/../etc/py
echo -e "\e[33mFinished.\e[0m"
