#!/usr/bin/env bash
# CONFIGPATH V1P1
set -eu
cd INSTALLER
INPATH="${PATH}"
path_sh="../etc/path.sh"
if ! [ -f "${path_sh}" ]; then
	mkdir -p ../etc
	touch "${path_sh}"
else
	. "${path_sh}"
fi
#=====os=====
if [ -z "${myos:-}" ]; then
	os_type=$(uname -mrs)
	echo "Current OS: ${os_type}"
	os_type_main=$(echo ${os_type} | cut -f 1 -d ' ')
	os_type_version=$(echo ${os_type} | cut -f 2 -d ' ')
	echo "myos=\"${os_type_main}\" #${os_type_version}" >>"${path_sh}"
	unset os_type os_type_main os_type_version
fi
#=====path=====
echo -e "\033[33mEnumerating valid path...\033[0m"
. ../lib/libpath
unset invalid_path duplicated_path
IFS=':'
eachpath=(${valid_path})
IFS=''
unset binpath
echo ${valid_path} | tr ':' '\n'
echo -e "\033[33mEnd locating valid path.\033[0m"
unset valid_path
for PROGNAME in ls grep sed rm python ps paeallel;do
	. exec/${PROGNAME}.sh
done
for PROGNAME in tar gtar gzip cp mv mkdir chmod chown zip unzip find sort cat split more cut head tail;do
	. exec/findcoreutils.sh
done
"${mysed}" -i 's;^gtar;tar;' "${path_sh}"
for PROGNAME in bgzip pigz xz bzip2 7z rar unrar ;do
	. exec/findornot.sh
done
. "${path_sh}"
echo -e "\033[33mAll configurations are printed as follows:\033[0m"
"${mycat}" "${path_sh}" | "${mygrep}" -v '^$' |"${mygrep}" -v '^#' | "${mysed}" 's/^my//' | "${mysed}" 's/=/\\\\033[33m in \\\\033[0m/ ' | "${mysed}" 's/ #/\\\\033[33m, \\\\033[32m/'| "${mysort}" | while read line; do echo -e "${line}\033[0m"; done
cd ..
